- hosts: palo
  connection: local

  vars:
    primary:
      ip_address: 192.168.15.151
    secondary:
      ip_address: 192.168.15.60
      
  tasks:
    - name: Suspend primary device
      paloaltonetworks.panos.panos_op:
        provider: '{{ primary }}'
        cmd: 'request high-availability state suspend'

    - name: Check that secondary is now active
      paloaltonetworks.panos.panos_op:
        provider: '{{ secondary }}'
        cmd: 'show high-availability state'
      register: secondary_active
      retries: 10
      delay: 30
      until: ( secondary_active.stdout | from_json).response.result.group["local-info"].state == 'active' and
             ( secondary_active.stdout | from_json).response.result.group["peer-info"].state == 'suspended' and
             ( secondary_active.stdout | from_json).response.result.group["peer-info"]["state-reason"] == 'User requested' # yamllint disable-line
   - name: show python lib/site paths
      python_requirements_info:
      register: pyinfo

   - name: Display Python Info 
      ansible.builtin.debug:
        msg: '{{ pyinfo.python }}'

