- name: Palo Alto Firewalls HA Pair
- hosts: '{{ target | default("ha_pair") }}'
  connection: local

  vars:
    primary:
      ip_address: '{{ primary_ip_address }}'
    secondary:
      ip_address: '{{ secondary_ip_address }}'
  roles:
    - Palo_ha



