---
- name: Suspend primary device
  paloaltonetworks.panos.panos_op:
    provider: '{{ primary }}'
    cmd: 'request high-availability state suspend'

- name: Check that secondary is now active
  paloaltonetworks.panos.panos_op:
    provider: '{{ secondary }}'
    cmd: 'show high-availability state'
  register: secondary_active
  retries: 10
  delay: 30
  until: ( secondary_active.stdout | from_json).response.result.group["local-info"].state == 'active' and
         ( secondary_active.stdout | from_json).response.result.group["peer-info"].state == 'suspended' and
         ( secondary_active.stdout | from_json).response.result.group["peer-info"]["state-reason"] == 'User requested' # yamllint disable-line


